"""empty message

Revision ID: 5f9b6189a99b
Revises: e7d3d99fba39
Create Date: 2026-01-10 02:43:48.104835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9b6189a99b'
down_revision = 'e7d3d99fba39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_column('assignment_date')

    # ### end Alembic commands ###
