"""empty message

Revision ID: 748b23b7c13b
Revises: db78473bd495
Create Date: 2026-01-12 04:32:06.726261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '748b23b7c13b'
down_revision = 'db78473bd495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
